### PR TITLE
Add support for log size limit

### PR DESCRIPTION
**Pull request by beschoenen**
Untested, based on this commit: https://github.com/devopsarr/terraform-provider-radarr/commit/899ff0327089e85d281932d174a8a7b2db1cb856

### CODE REVIEW

**Comment by Fuochi** [comment]
@beschoenen Hope you don't mind, since you've done most of the work, I used this 2 commits in #321

**Comment by beschoenen** [comment]
@Fuochi go for it, I realized it wasn't working because the sonarr-go lib was outdated still, so I closed it.

**Comment by Fuochi** [comment]
great, sonarr and prowlarr have a new releases that should work. Once I manage to find more time I'll do lidarr as well

**Comment by beschoenen** [comment]
Thank you for the effort!

**Pull request closed without merging**
